using System;
using UnityEngine;

namespace HutongGames.PlayMaker.Actions
{
	// Token: 0x020009C0 RID: 2496
	[ActionCategory(ActionCategory.GameObject)]
	[Tooltip("Spawns a random amount of chosen GameObject from global pool and fires them off in random directions. used for flashing geo generated by fragile greed.")]
	public class FlingFlashingGeo : RigidBody2dActionBase
	{
		// Token: 0x060036A9 RID: 13993 RVA: 0x0014293C File Offset: 0x00140B3C
		public override void Reset()
		{
			this.gameObject = null;
			this.spawnPoint = null;
			this.position = new FsmVector3
			{
				UseVariable = true
			};
			this.spawnMin = null;
			this.spawnMax = null;
			this.speedMin = null;
			this.speedMax = null;
			this.angleMin = null;
			this.angleMax = null;
			this.originVariationX = null;
			this.originVariationY = null;
		}

		// Token: 0x060036AA RID: 13994 RVA: 0x001429A4 File Offset: 0x00140BA4
		public override void OnEnter()
		{
			if (this.gameObject.Value != null)
			{
				Vector3 a = Vector3.zero;
				Vector3 zero = Vector3.zero;
				if (this.spawnPoint.Value != null)
				{
					a = this.spawnPoint.Value.transform.position;
					if (!this.position.IsNone)
					{
						a += this.position.Value;
					}
				}
				else if (!this.position.IsNone)
				{
					a = this.position.Value;
				}
				int num = UnityEngine.Random.Range(this.spawnMin.Value, this.spawnMax.Value + 1);
				for (int i = 1; i <= num; i++)
				{
					GameObject gameObject = this.gameObject.Value.Spawn(a, Quaternion.Euler(zero));
					float x = gameObject.transform.position.x;
					float y = gameObject.transform.position.y;
					float z = gameObject.transform.position.z;
					if (this.originVariationX != null)
					{
						x = gameObject.transform.position.x + UnityEngine.Random.Range(-this.originVariationX.Value, this.originVariationX.Value);
						this.originAdjusted = true;
					}
					if (this.originVariationY != null)
					{
						y = gameObject.transform.position.y + UnityEngine.Random.Range(-this.originVariationY.Value, this.originVariationY.Value);
						this.originAdjusted = true;
					}
					if (this.originAdjusted)
					{
						gameObject.transform.position = new Vector3(x, y, z);
					}
					base.CacheRigidBody2d(gameObject);
					float num2 = UnityEngine.Random.Range(this.speedMin.Value, this.speedMax.Value);
					float num3 = UnityEngine.Random.Range(this.angleMin.Value, this.angleMax.Value);
					this.vectorX = num2 * Mathf.Cos(num3 * 0.017453292f);
					this.vectorY = num2 * Mathf.Sin(num3 * 0.017453292f);
					Vector2 velocity;
					velocity.x = this.vectorX;
					velocity.y = this.vectorY;
					this.rb2d.velocity = velocity;
					gameObject.GetComponent<SpriteFlash>().GeoFlash();
				}
			}
			base.Finish();
		}

		// Token: 0x0400388B RID: 14475
		[RequiredField]
		[Tooltip("GameObject to spawn.")]
		public FsmGameObject gameObject;

		// Token: 0x0400388C RID: 14476
		[Tooltip("GameObject to spawn at (optional).")]
		public FsmGameObject spawnPoint;

		// Token: 0x0400388D RID: 14477
		[Tooltip("Position. If a Spawn Point is defined, this is used as a local offset from the Spawn Point position.")]
		public FsmVector3 position;

		// Token: 0x0400388E RID: 14478
		[Tooltip("Minimum amount of objects to be spawned.")]
		public FsmInt spawnMin;

		// Token: 0x0400388F RID: 14479
		[Tooltip("Maximum amount of objects to be spawned.")]
		public FsmInt spawnMax;

		// Token: 0x04003890 RID: 14480
		[Tooltip("Minimum speed objects are fired at.")]
		public FsmFloat speedMin;

		// Token: 0x04003891 RID: 14481
		[Tooltip("Maximum speed objects are fired at.")]
		public FsmFloat speedMax;

		// Token: 0x04003892 RID: 14482
		[Tooltip("Minimum angle objects are fired at.")]
		public FsmFloat angleMin;

		// Token: 0x04003893 RID: 14483
		[Tooltip("Maximum angle objects are fired at.")]
		public FsmFloat angleMax;

		// Token: 0x04003894 RID: 14484
		[Tooltip("Randomises spawn points of objects within this range. Leave as 0 and all objects will spawn at same point.")]
		public FsmFloat originVariationX;

		// Token: 0x04003895 RID: 14485
		public FsmFloat originVariationY;

		// Token: 0x04003896 RID: 14486
		private float vectorX;

		// Token: 0x04003897 RID: 14487
		private float vectorY;

		// Token: 0x04003898 RID: 14488
		private bool originAdjusted;
	}
}
